services:
  mongodb:
    build: ./mongodb
    container_name: mongodb_container
    user: "999:999"
    networks:
      - server_net
    volumes:
      - mongo-data:/data/db
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: "json-file"

  server:
    build: ./server
    container_name: node_backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/zero_trust_project
      - PORT=5000
      - PORTCLIENT=5173
      - JWT_SECRET=maSuperCleSecreteTresLongueEtAleatoire
      - PORT=5000
    networks:
      - client_net
      - server_net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: react_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    networks:
      - client_net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  client_net:
    driver: bridge
  server_net:
    driver: bridge

volumes:
  mongo-data: