services:
  mongodb_container:
    image: mongo:latest
    container_name: conteneur_db
    user: "999:999"
    command:
      - --tlsMode
      - requireTLS
      - --tlsCertificateKeyFile
      - /etc/ssl/mongodb.pem
      - --tlsCAFile
      - /etc/ssl/ca.crt
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./certs/mongodb.pem:/etc/ssl/mongodb.pem:ro
      - ./certs/ca.crt:/etc/ssl/ca.crt:ro
    networks:
      - server_net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  server:
    build: ./server
    container_name: conteneur_app
    image: server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/zero_trust_project?tls=true&authSource=admin
      - PORT=5000
      - PORTCLIENT=5173
      - JWT_SECRET=maSuperCleSecreteTresLongueEtAleatoire
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./certs:/app/certs:ro
    networks:
      - client_net
      - server_net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    depends_on:
      - mongodb_container

  client:
    build: ./client
    container_name: conteneur_web
    image: client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://localhost:5000/api
    networks:
      - client_net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL


networks:
  client_net:
    driver: bridge
  server_net:
    driver: bridge

volumes:
  mongo-data: